[package]
name = "wadlauncher"
version = "0.2.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
confy = "1.0.0"
serde = "^1.0"
serde_derive = "^1.0"
tinyfiledialogs = "3.9.1"
regex = "1.10"
wad = "0.3.2"
arboard = "3.6.0"

[profile.release]
strip = "symbols"
